import Lab3

print('\nEx:1')
Lab3.ex1()
print('\nEx:2')
Lab3.ex2()
print('\nEx:3 Non reccursive')
Lab3.ex3(reccursive=False)
print('\nEx:3 Reccursive')
Lab3.ex3(reccursive=True)
print('\nEx:4')
Lab3.ex4()
print('\nEx:5')
Lab3.ex5()
print('\nEx:6')
Lab3.ex6()
print('\nEx:7')
Lab3.ex7()
print('\nEx:8')
Lab3.ex8()
print('Ex:9\n')
Lab3.ex9()